### ISSUE TITLE
Add instructions for .gitattributes files

### ISSUE THREAD

**Issue by amahpour** [joerg/LabViewGitEnv#10]
In order for git to understand the settings from LabViewGitEnv a .gitattributes file needs to be generated in your local repo. Add the following line to the file:
`*.vi diff=labview`

**Comment by joerg** [comment]
This should actually be taken care of in the LVInit.sh and the https://github.com/joerg/LabViewGitEnv/blob/windows/etc/LVGitAttributes.tpl. Are you sure you ran the Init properly?

**Comment by rcassani** [comment]
I had the same issue, these is the procedure I followed

## System-wide installation
On Git Bash
```
mkdir -p /usr/local
git clone -b windows git://github.com/joerg/LabViewGitEnv.git /usr/local/
cd /usr/local && git checkout -b local
```
Added the bin directory (below) to the system PATH, as I wanted to used the modification from PowerShell
```
C:\Program Files\Git\usr\local\bin
```

Finally on Git Bash
```
LVInit.sh --system
```
## Testing
In a already existent LabVIEW Git repo, I modified an VI
Then execute on PowerShell:
```
git diff
```
It ran with the default diff, indicating that **Binaries files A and B differ**
Then I tried:
```
git difftool --tool labview
```
This gave me this in LVCompare:
![Alt text](https://lh3.googleusercontent.com/IUys6R0_46VxOnRa9JKgqq_l5zx4k1HCuG-e84qjCSx1hzVOQTbA9w4dwnBosg27IRhkrT1OigWGtAg=w1920-h947)
Finally, to make it work, I modified the **`.gitattributes`** file (as @amahpour pointed) in my LabVIEW repo adding the line 
```
*.vi diff=labview
```
Executing: `git diff` runs correctly LVCompare

**Comment by joerg** [comment]
Hmm, maybe the GIT installation somehow changed. Could you check if you have a file /etc/gitattributes within you GIT installation? How did you install GIT?
