### ISSUE TITLE
Hard-coded lookup paths

### ISSUE THREAD

**Issue by amahpour** [joerg/LabViewGitEnv#9]
The paths looking for all the LV sh scripts is hard-coded to ~/ which means you need to clone this repo and move all the contents directly into your home directory. My fix was to modify all the hard links. An example from [LVInit.sh](https://github.com/joerg/LabViewGitEnv/blob/windows/bin/LVInit.sh#L4) would be changing:
`GIT_ATTR=$(cat ~/etc/LVGitAttributes.tpl 2>/dev/null || cat /usr/local/etc/LVGitAttributes.tpl 2>/dev/null)`
to
`GIT_ATTR=$(cat ~/LabViewGitEnv/etc/LVGitAttributes.tpl 2>/dev/null || cat /usr/local/etc/LVGitAttributes.tpl 2>/dev/null)`
had you just cloned the repo directly into your home directory.

**Comment by joerg** [comment]
If you want, you could change all the scripts to use relative paths and have the absolute path auto generated by doing something line $(dirname $0). Again, since I am not actively working on this any more I will gladly accept pull requests.
